"""CLI Config Module - Re-exports from prometheus.config for backwards compatibility."""

from prometheus.config import (
    DEFAULT_CONFIG,
    PrometheusConfig,
    _sanitize_env_lines,
    cfg_get,
    check_config_version,
    ensure_prometheus_home,
    get_compatible_custom_providers,
    get_config_path,
    get_env_path,
    get_env_value,
    get_managed_update_command,
    get_project_root,
    get_prometheus_home,
    load_config,
    migrate_config,
    migrate_json_to_yaml,
    read_raw_config,
    recommended_update_command,
    remove_env_value,
    save_config,
    save_env_value,
    validate_config_structure,
)

__all__ = [
    "PrometheusConfig",
    "cfg_get",
    "DEFAULT_CONFIG",
    "get_prometheus_home",
    "get_config_path",
    "get_env_path",
    "load_config",
    "save_config",
    "save_env_value",
    "remove_env_value",
    "get_env_value",
    "ensure_prometheus_home",
    "get_project_root",
    "check_config_version",
    "migrate_config",
    "validate_config_structure",
    "get_compatible_custom_providers",
    "recommended_update_command",
    "get_managed_update_command",
    "read_raw_config",
    "_sanitize_env_lines",
    "migrate_json_to_yaml",
]
