from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class ModelMetadata:
    id: str
    provider: str
    context_length: int
    max_output_tokens: int
    supports_vision: bool
    supports_tools: bool
    supports_streaming: bool
    training_cutoff: str
    pricing_input: float
    pricing_output: float
    description: str


MODEL_METADATA: Dict[str, ModelMetadata] = {
    "gpt-4o": ModelMetadata(
        id="gpt-4o",
        provider="openai",
        context_length=128000,
        max_output_tokens=16384,
        supports_vision=True,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-04",
        pricing_input=2.50,
        pricing_output=10.00,
        description="GPT-4 Omni - multimodal flagship model",
    ),
    "gpt-4o-mini": ModelMetadata(
        id="gpt-4o-mini",
        provider="openai",
        context_length=128000,
        max_output_tokens=16384,
        supports_vision=True,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-04",
        pricing_input=0.15,
        pricing_output=0.60,
        description="GPT-4 Omni Mini - cost-efficient multimodal",
    ),
    "gpt-4-turbo": ModelMetadata(
        id="gpt-4-turbo",
        provider="openai",
        context_length=128000,
        max_output_tokens=4096,
        supports_vision=True,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2023-12",
        pricing_input=10.00,
        pricing_output=30.00,
        description="GPT-4 Turbo - enhanced GPT-4",
    ),
    "gpt-4": ModelMetadata(
        id="gpt-4",
        provider="openai",
        context_length=8192,
        max_output_tokens=4096,
        supports_vision=False,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2023-03",
        pricing_input=30.00,
        pricing_output=60.00,
        description="GPT-4 base model",
    ),
    "gpt-3.5-turbo": ModelMetadata(
        id="gpt-3.5-turbo",
        provider="openai",
        context_length=16385,
        max_output_tokens=4096,
        supports_vision=False,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2023-09",
        pricing_input=0.50,
        pricing_output=1.50,
        description="GPT-3.5 Turbo - fast and affordable",
    ),
    "o1": ModelMetadata(
        id="o1",
        provider="openai",
        context_length=200000,
        max_output_tokens=100000,
        supports_vision=True,
        supports_tools=False,
        supports_streaming=False,
        training_cutoff="2024-04",
        pricing_input=15.00,
        pricing_output=60.00,
        description="O1 - reasoning model for complex tasks",
    ),
    "o1-mini": ModelMetadata(
        id="o1-mini",
        provider="openai",
        context_length=128000,
        max_output_tokens=65536,
        supports_vision=False,
        supports_tools=False,
        supports_streaming=False,
        training_cutoff="2024-09",
        pricing_input=3.00,
        pricing_output=12.00,
        description="O1 Mini - efficient reasoning model",
    ),
    "o3-mini": ModelMetadata(
        id="o3-mini",
        provider="openai",
        context_length=200000,
        max_output_tokens=100000,
        supports_vision=True,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-09",
        pricing_input=1.10,
        pricing_output=4.40,
        description="O3 Mini - advanced reasoning with tools",
    ),
    "claude-3.5-sonnet": ModelMetadata(
        id="claude-3.5-sonnet",
        provider="anthropic",
        context_length=200000,
        max_output_tokens=8192,
        supports_vision=True,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-04",
        pricing_input=3.00,
        pricing_output=15.00,
        description="Claude 3.5 Sonnet - balanced performance",
    ),
    "claude-3.5-sonnet-v2": ModelMetadata(
        id="claude-3.5-sonnet-v2",
        provider="anthropic",
        context_length=200000,
        max_output_tokens=8192,
        supports_vision=True,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-10",
        pricing_input=3.00,
        pricing_output=15.00,
        description="Claude 3.5 Sonnet v2 - improved coding",
    ),
    "claude-3-opus": ModelMetadata(
        id="claude-3-opus",
        provider="anthropic",
        context_length=200000,
        max_output_tokens=4096,
        supports_vision=True,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2023-08",
        pricing_input=15.00,
        pricing_output=75.00,
        description="Claude 3 Opus - most capable Claude",
    ),
    "claude-3-haiku": ModelMetadata(
        id="claude-3-haiku",
        provider="anthropic",
        context_length=200000,
        max_output_tokens=4096,
        supports_vision=True,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2023-08",
        pricing_input=0.25,
        pricing_output=1.25,
        description="Claude 3 Haiku - fast and affordable",
    ),
    "claude-3.5-haiku": ModelMetadata(
        id="claude-3.5-haiku",
        provider="anthropic",
        context_length=200000,
        max_output_tokens=8192,
        supports_vision=True,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-10",
        pricing_input=0.80,
        pricing_output=4.00,
        description="Claude 3.5 Haiku - improved efficiency",
    ),
    "gemini-2.0-flash": ModelMetadata(
        id="gemini-2.0-flash",
        provider="google",
        context_length=1048576,
        max_output_tokens=8192,
        supports_vision=True,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-06",
        pricing_input=0.10,
        pricing_output=0.40,
        description="Gemini 2.0 Flash - fast multimodal",
    ),
    "gemini-2.0-flash-lite": ModelMetadata(
        id="gemini-2.0-flash-lite",
        provider="google",
        context_length=1048576,
        max_output_tokens=8192,
        supports_vision=True,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-06",
        pricing_input=0.075,
        pricing_output=0.30,
        description="Gemini 2.0 Flash Lite - most cost-efficient",
    ),
    "gemini-1.5-pro": ModelMetadata(
        id="gemini-1.5-pro",
        provider="google",
        context_length=2097152,
        max_output_tokens=8192,
        supports_vision=True,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-02",
        pricing_input=1.25,
        pricing_output=5.00,
        description="Gemini 1.5 Pro - long context champion",
    ),
    "gemini-1.5-flash": ModelMetadata(
        id="gemini-1.5-flash",
        provider="google",
        context_length=1048576,
        max_output_tokens=8192,
        supports_vision=True,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-02",
        pricing_input=0.075,
        pricing_output=0.30,
        description="Gemini 1.5 Flash - fast and efficient",
    ),
    "deepseek-chat": ModelMetadata(
        id="deepseek-chat",
        provider="deepseek",
        context_length=64000,
        max_output_tokens=4096,
        supports_vision=False,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-05",
        pricing_input=0.14,
        pricing_output=0.28,
        description="DeepSeek Chat - affordable Chinese model",
    ),
    "deepseek-v3": ModelMetadata(
        id="deepseek-v3",
        provider="deepseek",
        context_length=64000,
        max_output_tokens=4096,
        supports_vision=False,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-12",
        pricing_input=0.27,
        pricing_output=1.10,
        description="DeepSeek V3 - advanced reasoning",
    ),
    "deepseek-reasoner": ModelMetadata(
        id="deepseek-reasoner",
        provider="deepseek",
        context_length=64000,
        max_output_tokens=4096,
        supports_vision=False,
        supports_tools=False,
        supports_streaming=True,
        training_cutoff="2024-12",
        pricing_input=0.55,
        pricing_output=2.19,
        description="DeepSeek Reasoner - chain-of-thought",
    ),
    "grok-2": ModelMetadata(
        id="grok-2",
        provider="xai",
        context_length=131072,
        max_output_tokens=8192,
        supports_vision=True,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-07",
        pricing_input=2.00,
        pricing_output=10.00,
        description="Grok 2 - X.AI flagship model",
    ),
    "grok-2-mini": ModelMetadata(
        id="grok-2-mini",
        provider="xai",
        context_length=131072,
        max_output_tokens=8192,
        supports_vision=False,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-07",
        pricing_input=0.20,
        pricing_output=1.00,
        description="Grok 2 Mini - efficient X.AI model",
    ),
    "llama-3.1-405b": ModelMetadata(
        id="llama-3.1-405b",
        provider="meta",
        context_length=131072,
        max_output_tokens=4096,
        supports_vision=False,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-07",
        pricing_input=2.00,
        pricing_output=2.00,
        description="Llama 3.1 405B - largest open model",
    ),
    "llama-3.1-70b": ModelMetadata(
        id="llama-3.1-70b",
        provider="meta",
        context_length=131072,
        max_output_tokens=4096,
        supports_vision=False,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-07",
        pricing_input=0.35,
        pricing_output=0.40,
        description="Llama 3.1 70B - balanced open model",
    ),
    "llama-3.1-8b": ModelMetadata(
        id="llama-3.1-8b",
        provider="meta",
        context_length=131072,
        max_output_tokens=4096,
        supports_vision=False,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-07",
        pricing_input=0.05,
        pricing_output=0.08,
        description="Llama 3.1 8B - lightweight open model",
    ),
    "llama-3.2-90b-vision": ModelMetadata(
        id="llama-3.2-90b-vision",
        provider="meta",
        context_length=131072,
        max_output_tokens=4096,
        supports_vision=True,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-09",
        pricing_input=0.90,
        pricing_output=0.90,
        description="Llama 3.2 90B Vision - multimodal open",
    ),
    "llama-3.2-11b-vision": ModelMetadata(
        id="llama-3.2-11b-vision",
        provider="meta",
        context_length=131072,
        max_output_tokens=4096,
        supports_vision=True,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-09",
        pricing_input=0.055,
        pricing_output=0.055,
        description="Llama 3.2 11B Vision - efficient multimodal",
    ),
    "mistral-large": ModelMetadata(
        id="mistral-large",
        provider="mistral",
        context_length=128000,
        max_output_tokens=4096,
        supports_vision=False,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-07",
        pricing_input=2.00,
        pricing_output=6.00,
        description="Mistral Large - flagship Mistral model",
    ),
    "mistral-medium": ModelMetadata(
        id="mistral-medium",
        provider="mistral",
        context_length=128000,
        max_output_tokens=4096,
        supports_vision=False,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-07",
        pricing_input=0.70,
        pricing_output=2.10,
        description="Mistral Medium - balanced Mistral model",
    ),
    "mistral-small": ModelMetadata(
        id="mistral-small",
        provider="mistral",
        context_length=128000,
        max_output_tokens=4096,
        supports_vision=False,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-07",
        pricing_input=0.20,
        pricing_output=0.60,
        description="Mistral Small - efficient Mistral model",
    ),
    "codestral": ModelMetadata(
        id="codestral",
        provider="mistral",
        context_length=256000,
        max_output_tokens=8192,
        supports_vision=False,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-05",
        pricing_input=0.30,
        pricing_output=0.90,
        description="Codestral - code-specialized model",
    ),
    "command-r": ModelMetadata(
        id="command-r",
        provider="cohere",
        context_length=128000,
        max_output_tokens=4096,
        supports_vision=False,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-03",
        pricing_input=0.50,
        pricing_output=1.50,
        description="Command R - retrieval-optimized model",
    ),
    "command-r-plus": ModelMetadata(
        id="command-r-plus",
        provider="cohere",
        context_length=128000,
        max_output_tokens=4096,
        supports_vision=False,
        supports_tools=True,
        supports_streaming=True,
        training_cutoff="2024-04",
        pricing_input=3.00,
        pricing_output=15.00,
        description="Command R+ - enhanced retrieval model",
    ),
}


def get_model_metadata(model_id: str) -> ModelMetadata | None:
    return MODEL_METADATA.get(model_id)


def get_context_length(model_id: str) -> int:
    metadata = get_model_metadata(model_id)
    if metadata:
        return metadata.context_length
    return 4096


def get_pricing(model_id: str) -> Dict[str, float]:
    metadata = get_model_metadata(model_id)
    if metadata:
        return {
            "input": metadata.pricing_input,
            "output": metadata.pricing_output,
        }
    return {"input": 0.0, "output": 0.0}


def supports_feature(model_id: str, feature: str) -> bool:
    metadata = get_model_metadata(model_id)
    if not metadata:
        return False

    feature_map: Dict[str, Any] = {
        "vision": metadata.supports_vision,
        "tools": metadata.supports_tools,
        "streaming": metadata.supports_streaming,
    }

    return feature_map.get(feature, False)
